import Head from 'next/head';
import { PrismaClient, Post } from '@prisma/client';
import Link from 'next/link'

const prisma = new PrismaClient();

export const getStaticProps = async () => {
  const posts = await prisma.post.findMany();
  console.log(posts);
  return {
    props: {
      posts
    }
  };
}

export default function BlogPage({ posts }: { posts: Post[] }) {
  return (
    <>
      <Head>
        <title>My Blog Posts </title>
        < meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/">
        <a className="cursor-pointer underline" > Go to home </a>
      </Link>
      < br />
      <ul className="">
        {
          posts.map(({ id, title, excerpt }) => (
            <>
              <br />
              <li className="" key={id}>
                {title}
                < br />
                {id}
                < br />
                {excerpt}
                < br />
                <Link href={`/posts/${id}`}>
                  <a className="cursor-pointer underline" > Go to Post </a>

                </Link>
              </li>
            </>
          ))
        }
      </ul>
    </>
  )
}
