import Head from 'next/head';
import Image from 'next/image';
import {PrismaClient} from '@prisma/client';
import Link from 'next/link'

const prisma = new PrismaClient();

export const getStaticProps = async() => {
  const posts = await prisma.post.findMany();
  return {
    props: {
      posts
    }
  };
}

export default function Home({posts}) {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href={`/test`}>
        <a>Go to Test</a>
      </Link>
      <ul className="">
      {posts.map(({ id, title, excerpt }) => (
        <li className="" key={id}>
          <Link href={`/post/${id}`}>
            <a>Go to Post</a>
          </Link>
          <br />
          {title}
          <br />
          {id}
          <br />
          {excerpt}
        </li>
      ))}
    </ul>
  </div>
  )
}
