import Head from 'next/head';
import Image from 'next/image';
//import {PrismaClient} from '@prisma/client';
import Link from 'next/link' 

export default function Test() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/">
        <a>Back to home</a>
      </Link>
    </div>
  )
}
